language: php
sudo: false

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_install:
  - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{,.disabled} || echo "xdebug not available"
  - composer self-update

install:
  - composer install

script:
  - ./vendor/bin/phpunit

jobs:
  include:
    - stage: Test
      name: Lowest dependencies
      php: 7.1
      install: composer update --prefer-dist --prefer-lowest
