services:
    ttskch_pagerfanta.config:
        public: true
        class: Ttskch\PagerfantaBundle\Config
        properties:
            pageName: '%ttskch_pagerfanta.page.name%'
            pageRange: '%ttskch_pagerfanta.page.range%'
            limitName: '%ttskch_pagerfanta.limit.name%'
            limitDefault: '%ttskch_pagerfanta.limit.default%'
            sortKeyName: '%ttskch_pagerfanta.sort.key.name%'
            sortDirectionName: '%ttskch_pagerfanta.sort.direction.name%'
            sortDirectionDefault: '%ttskch_pagerfanta.sort.direction.default%'
            templatePager: '%ttskch_pagerfanta.template.pager%'
            templateSortable: '%ttskch_pagerfanta.template.sortable%'

    ttskch_pagerfanta.context:
        public: true
        class: Ttskch\PagerfantaBundle\Context
        arguments:
            - '@ttskch_pagerfanta.config'
            - '@request_stack'
            - '@form.factory'

    Ttskch\PagerfantaBundle\Twig\PagerfantaExtension:
        tags: { name: twig.extension }
        arguments:
            - '@ttskch_pagerfanta.context'
            - '@twig'

    # alias for autowiring
    Ttskch\PagerfantaBundle\Context: '@ttskch_pagerfanta.context'
